### ISSUE TITLE
Test plan tracking issue

### ISSUE THREAD

**Issue by domenic** [mikewest/origin-policy#92]
I want to use this issue to compile web platform tests that need to be written. Currently we are writing tests as part of the Chromium implementation, but some things are not naturally tested, e.g. we get them automatically so we aren't introducing tests alongside appropriate code changes.

I intend to edit this post frequently. Feel free to post your own suggestions.

- [X] [MIME type checking](https://github.com/web-platform-tests/wpt/blob/master/origin-policy/bad-server/manifest-mimetype.https.html)
- [X] [Status code checking](https://github.com/web-platform-tests/wpt/blob/master/origin-policy/bad-server/manifest-404.https.html)
- [X] [FP](https://github.com/web-platform-tests/wpt/tree/master/origin-policy/features)/[CSP](https://github.com/web-platform-tests/wpt/tree/master/origin-policy/content-security) syntax in the manifest
- [X] [IDs](https://github.com/web-platform-tests/wpt/tree/master/origin-policy/ids) syntax in the manifest
- [ ] UTF-8 is always used despite BOM or Content-Type
- [ ] blob: URLs can get an origin policy applied. (Discussion in #84)
- [ ] CSP does not apply to the origin policy manifest fetch. (Discussion in #84)
- [ ] Origin policy is based on response URL, not document origin; in particular test sandboxed iframes and `window.open()` with no args. (Discussion in #81)
